//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_420_SkrylevaLianaAleksandrovna.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int id { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<bool> finish { get; set; }
        public Nullable<int> idTournament { get; set; }
    
        public virtual Tournament Tournament { get; set; }
    }
}
