//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_420_SkrylevaLianaAleksandrovna.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Participant()
        {
            this.Statistic = new HashSet<Statistic>();
        }
    
        public int id { get; set; }
        public Nullable<int> idRole { get; set; }
        public Nullable<int> rang { get; set; }
        public Nullable<int> idParty { get; set; }
        public Nullable<int> idTournament { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> played { get; set; }
        public string login { get; set; }
        public Nullable<int> password { get; set; }
        public string fio { get; set; }
        public string nick { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual Role Role { get; set; }
        public virtual Tournament Tournament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Statistic> Statistic { get; set; }
    }
}
